<?php

return [
    [
        'key'        => 'dashboard',
        'name'       => 'admin::app.layouts.dashboard',
        'route'      => 'admin.dashboard.index',
        'sort'       => 1,
        'icon-class' => 'mdi-grid',
    ], 
    // [
    //     'key'        => 'task',
    //     'name'       => 'task',
    //     'route'      => 'admin.task.index',
    //     'sort'       => 1,
    //     'icon-class' => 'mdi-calendar-check-outline',
    // ],
     [
        'key'        => 'leads',
        'name'       => 'admin::app.layouts.leads',
        'route'      => 'admin.leads.index',
        'sort'       => 2,
        'icon-class' => 'mdi-account-card-details',
    ], [
        'key'        => 'customers',
        'name'       => 'customers',
        'route'      => 'admin.customers.index',
        'sort'       => 3,
        'icon-class' => 'mdi-account-group',
    ], [
        'key'        => 'mail',
        'name'       => 'admin::app.layouts.mail.title',
        'route'      => 'admin.mail.index',
        'params'     => ['route' => 'inbox'],
        'sort'       => 4,
        'icon-class' => 'mdi-email-outline',
    ], [
        'key'        => 'mail.compose',
        'name'       => 'admin::app.layouts.mail.compose',
        'route'      => 'admin.mail.index',
        'params'     => ['route' => 'compose'],
        'sort'       => 1,
    ], [
        'key'        => 'mail.inbox',
        'name'       => 'admin::app.layouts.mail.inbox',
        'route'      => 'admin.mail.index',
        'params'     => ['route' => 'inbox'],
        'sort'       => 2,
    ], [
        'key'        => 'mail.draft',
        'name'       => 'admin::app.layouts.mail.draft',
        'route'      => 'admin.mail.index',
        'params'     => ['route' => 'draft'],
        'sort'       => 3,
    ], [
        'key'        => 'mail.outbox',
        'name'       => 'admin::app.layouts.mail.outbox',
        'route'      => 'admin.mail.index',
        'params'     => ['route' => 'outbox'],
        'sort'       => 4,
    ], [
        'key'        => 'mail.sent',
        'name'       => 'admin::app.layouts.mail.sent',
        'route'      => 'admin.mail.index',
        'params'     => ['route' => 'sent'],
        'sort'       => 4,
    ], [
        'key'        => 'mail.trash',
        'name'       => 'admin::app.layouts.mail.trash',
        'route'      => 'admin.mail.index',
        'params'     => ['route' => 'trash'],
        'sort'       => 5,
    ], 
    // [
    //     'key'        => 'activities',
    //     'name'       => 'admin::app.layouts.activities',
    //     'route'      => 'admin.activities.index',
    //     'sort'       => 5,
    //     'icon-class' => 'mdi-lightbulb-outline',
    // ], 
    // [
    //     'key'        => 'reports',
    //     'name'       => 'reports',
    //     'route'      => 'admin.reports.index',
    //     'sort'       => 5,
    //     'icon-class' => 'mdi-chart-areaspline',
    // ], 
    [
        'key'        => 'compensation',
        'name'       => 'compensation',
        'route'      => 'admin.compensations.index',
        'sort'       => 5,
        'icon-class' => 'mdi-cash-100',
    ], 
    [
        'key'        => 'automation',
        'name'       => 'automation',
        'route'      => 'admin.automation.index',
        'sort'       => 5,
        'icon-class' => 'mdi-rocket',
    ], 
    [
        'key'        => 'conversations',
        'name'       => 'conversations',
        'route'      => 'admin.conversations.index',
        'sort'       => 5,
        'icon-class' => 'mdi-chat',
    ], 
    // [
    //     'key'        => 'contacts',
    //     'name'       => 'admin::app.layouts.contacts',
    //     'route'      => 'admin.contacts.persons.index',
    //     'sort'       => 6,
    //     'icon-class' => 'mdi-phone',
    // ], 
    // [
    //     'key'        => 'contacts.persons',
    //     'name'       => 'admin::app.layouts.persons',
    //     'route'      => 'admin.contacts.persons.index',
    //     'sort'       => 1,
    // ], 
    // [
    //     'key'        => 'contacts.organizations',
    //     'name'       => 'admin::app.layouts.organizations',
    //     'route'      => 'admin.contacts.organizations.index',
    //     'sort'       => 2,
    // ], 
    // [
    //     'key'        => 'products',
    //     'name'       => 'admin::app.layouts.products',
    //     'route'      => 'admin.products.index',
    //     'sort'       => 7,
    //     'icon-class' => 'mdi-archive',
    // ], 
    [
        'key'        => 'settings',
        'name'       => 'admin::app.layouts.settings',
        'route'      => 'admin.settings.index',
        'sort'       => 8,
        'icon-class' => 'mdi-settings',
    ], [
        'key'        => 'settings.user',
        'name'       => 'admin::app.layouts.user',
        'route'      => 'admin.settings.groups.index',
        'info'       => 'admin::app.layouts.user-info',
        'sort'       => 1,
    ], [
        'key'        => 'settings.user.groups',
        'name'       => 'admin::app.layouts.groups',
        'info'       => 'admin::app.layouts.groups-info',
        'route'      => 'admin.settings.groups.index',
        'sort'       => 1,
        'icon-class' => 'icon group-icon',
    ], [
        'key'        => 'settings.user.roles',
        'name'       => 'admin::app.layouts.roles',
        'info'       => 'admin::app.layouts.roles-info',
        'route'      => 'admin.settings.roles.index',
        'sort'       => 2,
        'icon-class' => 'role-icon',
    ], [
        'key'        => 'settings.user.users',
        'name'       => 'admin::app.layouts.users',
        'info'       => 'admin::app.layouts.users-info',
        'route'      => 'admin.settings.users.index',
        'sort'       => 3,
        'icon-class' => 'icon user-icon',
    ], [
        'key'        => 'settings.lead',
        'name'       => 'admin::app.layouts.lead',
        'info'       => 'admin::app.layouts.lead-info',
        'route'      => 'admin.settings.pipelines.index',
        'sort'       => 2,
    ], [
        'key'        => 'settings.lead.pipelines',
        'name'       => 'admin::app.layouts.pipelines',
        'info'       => 'admin::app.layouts.pipelines-info',
        'route'      => 'admin.settings.pipelines.index',
        'sort'       => 1,
        'icon-class' => 'icon pipeline-icon',
    ], [
        'key'        => 'settings.lead.sources',
        'name'       => 'admin::app.layouts.sources',
        'info'       => 'admin::app.layouts.sources-info',
        'route'      => 'admin.settings.sources.index',
        'sort'       => 2,
        'icon-class' => 'icon source-icon',
    ], [
        'key'        => 'settings.lead.types',
        'name'       => 'admin::app.layouts.types',
        'info'       => 'admin::app.layouts.types-info',
        'route'      => 'admin.settings.types.index',
        'sort'       => 3,
        'icon-class' => 'icon type-icon',
    ], [
        'key'        => 'settings.automation',
        'name'       => 'admin::app.layouts.automation',
        'info'       => 'admin::app.layouts.automation-info',
        'route'      => 'admin.settings.attributes.index',
        'sort'       => 3,
    ], [
        'key'        => 'settings.automation.attributes',
        'name'       => 'admin::app.layouts.attributes',
        'info'       => 'admin::app.layouts.attributes-info',
        'route'      => 'admin.settings.attributes.index',
        'sort'       => 1,
        'icon-class' => 'icon attribute-icon',
    ], [
        'key'        => 'settings.automation.email_templates',
        'name'       => 'admin::app.layouts.email-templates',
        'info'       => 'admin::app.layouts.email-templates-info',
        'route'      => 'admin.settings.email_templates.index',
        'sort'       => 2,
        'icon-class' => 'icon email-template-icon',
    ], [
        'key'        => 'settings.automation.workflows',
        'name'       => 'admin::app.layouts.workflows',
        'info'       => 'admin::app.layouts.workflows-info',
        'route'      => 'admin.settings.workflows.index',
        'sort'       => 3,
        'icon-class' => 'icon workflow-icon',
    ], [
        'key'        => 'settings.other_settings',
        'name'       => 'admin::app.layouts.other-settings',
        'info'       => 'admin::app.layouts.other-settings-info',
        'route'      => 'admin.settings.tags.index',
        'sort'       => 4,
        'icon-class' => 'icon settings-icon',
    ], [
        'key'        => 'settings.other_settings.tags',
        'name'       => 'admin::app.layouts.tags',
        'info'       => 'admin::app.layouts.tags-info',
        'route'      => 'admin.settings.tags.index',
        'sort'       => 1,
        'icon-class' => 'icon tag-icon',
    ], [
        'key'        => 'configuration',
        'name'       => 'admin::app.layouts.configuration',
        'route'      => 'admin.configuration.index',
        'sort'       => 9,
        'icon-class' => 'mdi-math-compass',
    ]
];